### ISSUE TITLE
Icons not appearing on-screen

### ISSUE THREAD

**Issue by Saraphima** [UltiNaruto/MPItemTracker#1]
The Icons disappear the moment I click onto dolphin after running the .exe

**Comment by UltiNaruto** [comment]
Hi,

Could you tell me on which version of Dolphin you tried?
Also which game it was and was the game running?

**Comment by Saraphima** [comment]
Dolphin 5.0-4869, its the version that has ubershaders. I was playing Metroid Prime 2 with randovania.

Also should note I figured out it only happened when I had dolphin in fullscreen. Once I turned that off the icons overlaid properly.

**Comment by UltiNaruto** [comment]
That's a quite old build of Dolphin. You should try updating to the latest beta somedays.
Fullscreen tends not to work properly due to how I draw the icons. Also on Discord it won't display properly aswell if you don't share the whole screen.
